#!/usr/bin/env bash

# Check if database name is provided as argument
if [ $# -ne 1 ]; then
  echo "Usage: $0 <database_name>"
  exit 1
fi

# Set database name
db_name=$1

# Query the database for documents with name starting by Holberton
mongo $db_name --eval 'db.school.find({"name":/^Holberton/})'

